[tasks.build-wasm-prod]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = [
    "build",
    ".",
    "--release",
    "--target",
    "web",
    "-d",
    "../../web/projects/wasm-example/src/lib/",
]

[tasks.build-wasm-dev]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = [
    "build",
    ".",
    "--target",
    "web",
    "-d",
    "../../web2/wasm-example/",
]

[tasks.prod-all]
dependencies = ["build-wasm-prod"]

[tasks.dev-all]
dependencies = ["build-wasm-dev"]