[tasks.build-wasm]
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "--help" }
command = "wasm-pack"
args = [
    "build",
    ".",
    "--release",
    "--target",
    "web",
    "-d",
    "../../projects/wasm-example/src/lib/",
]

[tasks.build-all]
dependencies = ["build-wasm"]

[tasks.watch]