// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "my_dotnet_lib";



        [DllImport(__DllName, EntryPoint = "factorial_cs", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong factorial_cs(int num);

        [DllImport(__DllName, EntryPoint = "add_one", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int add_one(int num);


    }



}
